# Generated by Django 4.0.1 on 2022-12-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
